title = "Distributed EDA config"

[eda]
	generations = 1000
	population = 10000
	tournament = 2
	output-probabilities = "./output-probabilities-eda"
	save-steps = 1000

[rules]
	input = "/home/jgcarvalho/gocode/src/github.com/jgcarvalho/zeca-create-rule/rose.rule"
	output = "./output-rules"

[db]
	db-dir = "/home/jgcarvalho/"
	db-name = "chameleonic.db"
	bucket-name = "proteins"
	init = "SeqHPRose"
	target = "All3HPRose"

[ca]
	steps = 1000
	ignore-steps = 100
